# Generated by Django 3.2.6 on 2021-08-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.CharField(max_length=50, verbose_name='عنوان توضیحات')),
                ('content_text', models.TextField(verbose_name='توضیحات')),
                ('image_content', models.ImageField(upload_to='media/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'توضیحات',
                'verbose_name_plural': 'توضیحات',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس های کاربران',
            },
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_footer', models.CharField(default=None, max_length=150, verbose_name='متن آخر صفحه')),
                ('url_field_tel', models.URLField(default=None, verbose_name='آدرس وب تلگرام')),
                ('url_field_insta', models.URLField(default=None, verbose_name='آدرس وب اینستاگرام')),
                ('url_field_google', models.URLField(default=None, verbose_name='آدرس وب گوگل درایو')),
                ('text_copyright', models.CharField(default=None, max_length=150, verbose_name='متن کپی رایت')),
            ],
            options={
                'verbose_name': 'آخر صفحه',
                'verbose_name_plural': 'آخر صفحه',
            },
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('logo_name', models.CharField(max_length=30, verbose_name='نام در نوبار')),
                ('name', models.CharField(max_length=30, verbose_name='اسم')),
                ('job_name', models.CharField(max_length=50, verbose_name='نام شغل')),
                ('url_content', models.URLField(verbose_name='آدرس وب')),
                ('image_content', models.ImageField(upload_to='media/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'صفحه ی خانه',
                'verbose_name_plural': 'صفحه ی خانه',
            },
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='media/', verbose_name='عکس نمونه ۱')),
                ('image_2', models.ImageField(upload_to='media/', verbose_name='عکس نمونه ۲')),
                ('image_3', models.ImageField(upload_to='media/', verbose_name='عکس نمونه ۳')),
                ('image_4', models.ImageField(upload_to='media/', verbose_name='عکس نمونه ۴')),
                ('image_5', models.ImageField(upload_to='media/', verbose_name='عکس نمونه ۵')),
                ('image_6', models.ImageField(upload_to='media/', verbose_name='عکس نمونه ۶')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس ها',
            },
        ),
    ]
